### ISSUE TITLE
config TypeScript

### ISSUE THREAD

**Issue by BrandonDHaskell** [Mike-415/BuzzMap#16]

**Comment by Mike-415** [comment]
- Ref: https://docs.expo.dev/guides/typescript/#in-an-existing-project
- go to Development and enter the following command "npx create-expo-app -t expo-template-blank-typescript"
- When you're adding a library, you need to enter '**npx expo install (library name)**'
- go to package.json and add the following to the 'scripts' portion
  - "scripts": {
    ** "ts:check": "tsc"**
    ...
    }
